### PR TITLE
include cerrno in common/thread/mutex_posix.c to resolve EBUSY error

### PR DESCRIPTION
**Pull request by cgb**
../../../../common/thread/mutex_posix.h:98: error: 'EBUSY' was not declared in this scope

### CODE REVIEW

**Comment by caladri** [comment]
Can you use <errno.h> instead of <cerrno> and update the pull request?  That would match the other code in WANProxy.  Thank you!  I have not done a pass over making sure things build on Linux lately.

**Comment by cgb** [comment]
Did you omit any words from 'Can you use instead of and update the pull request?' ? I'm not sure what you mean.  My C/C++ is relatively weak so you may have to spell it out to me.  Thanks :)

**Comment by caladri** [comment]
Sorry, din't expect that to be eaten!  errno.h instead of cerrno.

**Comment by caladri** [comment]
Merged with modifications, thanks!

**Pull request closed without merging**
